version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./index.html:/usr/share/nginx/html/index.html"
      - "./website1/:/usr/share/nginx/html/website1/"
      - "./website2/:/usr/share/nginx/html/website2/"