version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./40x.html:/usr/share/nginx/html/40x.html"
      - "./50x.html:/usr/share/nginx/html/50x.html"