version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - nginx-api-network

  api:
    container_name: backendapp
    image: shandysiswandi/learn-apigateway:latest
    networks:
      - nginx-api-network

networks:
  nginx-api-network:
    driver: bridge

