version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./domain1.html:/usr/share/nginx/html/domain1.com/index.html"
      - "./domain2.html:/usr/share/nginx/html/domain2.com/index.html"